web:
 image: webdevops/php-apache
 ports:
 - "15000:80"
 links:
 - db
 - db_ecommerce
 volumes:
 - ../$PWD/curso-php:/app/curso-php

db:
 image: mysql
 environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: dbphp7

db_ecommerce:
 image: mysql
 environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: db_ecommerce