version: '2'
services:
  web:
   image: webdevops/php-apache
   ports:
   - "15000:80"
   links:
   - db
   - db_ecommerce
   - db_sqlserver
   volumes:
   - ../curso-php:/app/curso-php
  ecommerce:
   image: webdevops/php-apache
   ports:
   - "80:80"
   links:
   - db_ecommerce
   volumes:
   - ./ecommerce:/app
  db:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: dbphp7
   volumes:
   - ./dumps/mysql/db:/dumps
  db_ecommerce:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: db_ecommerce
   volumes:
   - ./dumps/mysql/ecommerce:/dumps
  db_sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Root9876	
      MSSQL_PID: Developer
    ports:
    - "1401:1433"
    volumes:
    - ./dumps/sqlserver:/dumps