version: '2'
services:
  web:
   image: webdevops/php-apache
   ports:
   - "15000:80"
   links:
   - db
   - db_ecommerce
   - db_sqlserver
   volumes:
   - ../curso-php:/app/curso-php
  ecommerce:
   image: webdevops/php-apache
   ports:
   - "80:80"
   links:
   - db_ecommerce
   volumes:
   - ../curso-php/ecommerce:/app
  db:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: dbphp7
  db_ecommerce:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: db_ecommerce